apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-static
  namespace: nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1>Hello from k8s nignx argocd-1</h1>
    </body>
    </html>
